const menu = [
  {
    id: 1,
    title: "Idly",
    category: "breakfast",
    price: 70.0,
    img: "./images/item-1.jpeg",
    desc: `Idli is one of the most healthiest and popular South Indian breakfast dish. These are soft, light, fluffy steamed round cake made with a ground.`,
  },
  {
    id: 2,
    title: "South Indian Meals",
    category: "lunch",
    price: 150.0,
    img: "./images/item-2.jpeg",
    desc: `South Indian cooking is based around rice, lentils, and stews. Dishes such as dosa,idli, saaru/rasam,and huli/sambar are all from the South.`,
  },
  {
    id: 3,
    title: "keto chocolate milkshake",
    category: "shakes",
    price: 200.0,
    img: "./images/item-3.jpeg",
    desc: `Made from high quality South American cocoa butter, they're free of sugar alcohols, artificial sweeteners, soy, and palm oil. Best of all.`,
  },
  {
    id: 4,
    title: "Onion Dosa",
    category: "breakfast",
    price: 100.0,
    img: "./images/item-4.jpeg",
    desc: `Onion dosa is very easy simple yet delicious. It is a complete meal when served with any chutney or podi. The crispy dosa with sweetness of onions.`,
  },
  {
    id: 5,
    title: "Chicken Biriyani",
    category: "lunch",
    price: 350.0,
    img: "./images/item-5.jpeg",
    desc: `Chicken Biryani is a savory chicken and rice dish that includes layers of chicken, rice, and aromatics that are steamed together.`,
  },
  {
    id: 6,
    title: "oreo milkshake",
    category: "shakes",
    price: 220.0,
    img: "./images/item-6.jpeg",
    desc: `Oreo milkshake is the ideal sweet treat, loved by kids all over as well as adults.It is one of my favourite milkshakes and can be prepared in minutes.`,
  },
  {
    id: 7,
    title: "Rava Dosa",
    category: "breakfast",
    price: 100.0,
    img: "./images/item-7.jpeg",
    desc: `Rava dosa is a quick and popular variant of dosa from the South Indian cuisine. These are crispy, netted and thin crepes made with semolina.`,
  },
  {
    id: 8,
    title: "Chicken Friedrice",
    category: "lunch",
    price: 120.0,
    img: "./images/item-8.jpeg",
    desc: `Chicken fried rice is the comfort dish of Chinese food. It's been around for a very long time and is also common in East, Southeast, and South Asian cuisines.`,
  },
  {
    id: 9,
    title: "blue moon milkshake",
    category: "shakes",
    price: 180.0,
    img: "./images/item-9.jpeg",
    desc: `Some dairies that make Blue Moon keep their ingredients a secret, adding to the mystique. Varieties that have distinct berry or vanilla flavor.`,
  },
  {
    id: 10,
    title: "Podi Dosa",
    category: "breakfast",
    price: 100.0,
    img: "./images/item-10.jpeg",
    desc: `‘podidosa’, it is a spicy blend of spices and lentils that is so good on dosas. `,
  },
  {
    id: 11,
    title: "Veg Friedrice",
    category: "lunch",
    price: 80.0,
    img: "./images/item-11.jpeg",
    desc: `a popular and flavoured rice recipe made with cooked rice, finely chopped veggies and seasoning ingredients.`,
  },
];
export default menu;
